### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Kinrany** [kikito/middleclass#43]
Wiki homepage says that "The code is reasonably commented", but  middleclass.lua doesn't have a single comment. Am I missing something?

**Comment by kikito** [comment]
> Am I missing something?

You might have missed that [that particular wiki page was written in 2010](https://github.com/kikito/middleclass/wiki/Home/_history).

Things have changed a bit since then. I now believe that code should be written in a way that is self-explanatory, without relying on comments for clarity.

Please consider the Readme and the Wiki as the main documentation now. Even if I think the code is readable, I do understand that some people need to have something in natural language in order to get familiar with a system. 

I still think code is more reliable to written docs, mainly because it doesn't get "out of sync with reality", like docs do. This very issue is an example of that problem, in fact. [I have resynched it with reality](https://github.com/kikito/middleclass/wiki/Home/_compare/c61b7a05543ad05a62288f37629f8300f2c9930a...b0234cea555731f4ad995f18caac5c67cebb2949).

Thanks for helping me fix the problem, and have a good day!
