### ISSUE TITLE
What is the proper means of creating a module out of a middleclass class hierarchy

### ISSUE THREAD

**Issue by kmhappel** [kikito/middleclass#45]
I have built a class hierarchy with middleclass and it works magnificently until I try and turn it into a module. I am new to lua but not to oop. Most instructions I find for module creation seem to cause conflicts with my middleclass hierarchy. What is your recommended way of making middleclass based class hierarchies into modules so that huge code projects can be partitioned into modules and included in new code sections?

**Comment by kikito** [comment]
> Most instructions I find for module creation seem to cause conflicts with my middleclass hierarchy

You didn't say what you have tried, or what problems did you face, so I am risking giving you an incorrect answer, but here it is nonetheless: The way I recommend to structure classes in modules is: one class per module (per file), following this schema:

``` lua
-- car.lua

local class = require 'middleclass'
local Vehicle = require 'vehicle'

local Car = class('Car', Vehicle)

function Car:initialize(wheels, seats, doors)
  Vehicle.initialize(self)
  self.wheels = wheels
  self.seats = seats
  self.doors = doors
end
...
return Car
```

So the file `[my_class].lua` defines the class `MyClass`. It starts by requiring `middleclass`. It then requires any other dependencies it needs: other libraries, superclasses, other subclasses, etc. Then you define the class using middleclass, with the constructor, and as many methods as needed. Then you return the class, so it can be `require`d by other modules (like `Vehicle` is being required by `Car` on this example).

I think it is very important not to put classes or libraries in the global scope, and instead `require` them on every module where they are needed. This makes the dependencies of each module explicit. Using globals is exactly like using globals instead of parameters for a function; a recipe for disaster and subtle bugs.

I also recommend preferring composition to inheritance in general. If you must use inheritance, try to make your hierarchies shallow (with two or 3 levels tops) and thin (with not many classes per level).

I will close this issue now, please feel free to reopen if I didn't answer your question.

**Comment by kmhappel** [comment]
Thank You. I read module creation methods until my eyes rotated, lol. 
I am implementing a discovery in topological semiotics where inheritance makes sense because the entire structure is actually a consistent addressing scheme that normalizes distance and provides semantic comparison by detecting anomalies. A number of np hard problems have been resolved to linear time. I am actually a mathematician and haven't programmed in years since the days of c-front and Smalltalk when I worked with the Norwegians who wrote the original compiler in a Dutch company. Lua is wonderful and I have been able to implement green code for refactoring by more  experienced hands, giving a working description of behavior with test sets.

**Comment by kikito** [comment]
>discovery in topological semiotics where inheritance makes sense because the entire structure is actually a consistent addressing scheme that normalizes distance and provides semantic comparison by detecting anomalies.

That part probably makes total sense to you, but if you want to talk about it with non-expert on the field you might want to develop a simplified elevator pitch :). It sounds very interesting nonetheless - space representation is something I am interested about, although I have only implemented ad-hoc solutions in the context of videogames.

My point about inheritance is this: It is almost always a bet. Sometimes, you can be pretty certain that your future code will be organized in a hierarchy which matches your present code. (It sounds like that's your case, since the hierarchy is known in advance). But is not always the case. Refactoring code written with the wrong hierarchy criteria can be quite laborious. Given that lots of languages have inheritance in their front center, programmers in those languages tend to "default" to using it. So I always recommend giving composition a look first - to compensate.

>  I am actually a mathematician and haven't programmed in years since the days of c-front and Smalltalk when I worked with the Norwegians who wrote the original compiler in a Dutch company

Welcome back to the programming world! I hope you enjoy Lua :)
