### ISSUE TITLE
How to split a big class to several files?

### ISSUE THREAD

**Issue by jinq0123** [kikito/middleclass#48]
How to split `Game` class to several files?
* game.lua
* game_main_menu.lua
* game_options_menu.lua

```lua
local class = require("middleclass")
local Game = class("Game")

function Game:main_menu()
end

function Game:options_menu()
end

return Game
```

**Comment by Codinablack** [comment]
Change

local Game = class("Game") 

to

Game = class("Game") 

and you can use it in multiple files, ofc middleclass will still need to be loaded

**Comment by kikito** [comment]
I have several strategies for dealing with this.

First strategy is: not having big classes in the first place. A big class means that it is probably doing too much stuff. I try to use composition when possible (so instead of having a big object separated in two files, I would have two smaller classes separated into two files, and one of the classes would instantiate and use the other).

The second strategy is using [mixins](https://github.com/kikito/middleclass/wiki/Mixins). In middleclass, a mixin is a table with functions inside. Here are two mixins:

``` lua
-- game/main_menu.lua
local MainMenu = {
  show_main_menu = function()
    ...
  end,
  ...
}

return MainMenu
```

``` lua
-- game/options_menu.lua
local OptionsMenu = {
  show_options_menu = function()
    ...
  end,
  ...
}

return OptionsMenu
```

And here's how you would use it in a "Game" class:

``` lua
-- game.lua
local class = requie "middleclass"
local MainMenu = require "game.main_menu"
local OptionsMenu = require "game.options_menu"

local Game = class.new("MainMenu"):include(MainMenu, OptionsMenu)

...
local game = Game:new()
game:show_main_menu()
```

You could do the same with individual methods, as in your example (you could make `game_main_menu.lua` return a function, and then set it in the Game class by doing `Game.main_menu = game_main_menu`) but I think using mixins is less noisy and more powerful - you can group several functions in a single file this way.

A third option would be using [stateful.lua](https://github.com/kikito/stateful.lua). It is a mixin that "augments" classes with the possibility of having "states". Each state can have method called the same way. When you invoke a method on a stateful class, it invokes the method of the state marked as "current". I think it aligns well with a Game class:

``` lua
-- game/main_menu.lua
local MainMenu = {
  draw = function()
    ...
  end,
  ...
}

return MainMenu
```

``` lua
-- game/options_menu.lua
local OptionsMenu = {
  draw = function()
    ...
  end,
  ...
}

return OptionsMenu
```

``` lua
-- game.lua
local class = require "middleclass"
local Stateful = require "stateful"
local MainMenu = require "game.main_menu"
local OptionsMenu = require "game.options_menu"

local Game = class.new("MainMenu"):include(Stateful)

Game:addState('MainMenu', MainMenu)
Game:addState('OptionsMenu', OptionsMenu)

...

local game = Game:new()

game:gotoState('MainMenu')
game:draw() -- draws the MainMenu

game:gotoState('OptionsMenu')
game:draw() -- draws the OptionsMenu

...
local game = Game:new()
game:show_main_menu()
```

That's all. Sorry for this taking so long for me to answer, I just noticed this issue.
